#!/usr/bin/env bash
set -e # 에러 발생 시 스크립트 중단

DATEFMT=`date +%Y-%m-%d:%H:%M:%S`

mkdir .deploy
cd .deploy
git clone -b gh-pages "${GH_REPO}" gh-pages
rm -rf ./*
cp -r ../public/* .
git add -A .
git commit -m "Entry Document Update $DATEFMT"
git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages
