#!/usr/bin/env bash
set -e # 에러 발생 시 스크립트 중단

mkdir .deploy
cd .deploy
git clone --depth 1 --branch gh-pages --single-branch "https://${GH_TOKEN}@${GH_REF}"
rm -rf ./*
cp -r ../public/* .
git add -A .
git commit -m "Entry Document Update"
git branch -m gh-pages
git push -q -u origin gh-pages
